package lk.ijse.dep.pos.dao;

public enum DAOTypes {
    CUSTOMER,ITEM,ORDERLIST,ORDER,ORDER_DETAIL, QUERY,REPORT,TRANSDETAIL,GENACC,PURCHASE,PURORDERDETAIL,TRANSACTIONDETAIL,PACK,ORDERDETAIL, ODETAIL;

}
